apiVersion: apps/v1
kind: Deployment
metadata:
  name: akaunting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akaunting-app
  template:
    metadata:
      labels:
        app: akaunting-app
    spec:
      containers:
        - name: akaunting-app
          image: 24cstc/akaunting-app
          ports:
            - containerPort: 80 iguration
---
apiVersion: v1
kind: Service
metadata:
  name: akaunting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: akaunting-app
