apiVersion: apps/v1
kind: Deployment
metadata:
  name: akaunting-app
  labels:
    app: akaunting
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: akaunting
  template:
    metadata:
      labels:
        app: akaunting
    spec:
      containers:
        - name: akaunting
          image: 24cstc/cstc_akounting:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              value: "db"  
            - name: DB_USERNAME
              value: "usr"  
            - name: DB_PASSWORD
              value: "dbpas" 
            - name: ADMIN_EMAIL
              value: "@gm"  
            - name: ADMIN_PASSWORD
              value: "passwd"  
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage  
            - name: app-cache
              mountPath: /var/www/html/bootstrap/cache  
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-storage-pvc  
        - name: app-cache
          persistentVolumeClaim:
            claimName: app-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: akaunting-service
spec:
  selector:
    app: akaunting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
