name: CI AKAUNT

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      # Set up kubeconfig
      - name: Deploy to Kubernetes
        run: |
          echo "[+] Configuring Kub ..."
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          kubectl apply -f dep.yaml
          echo "Checking rollout status"
          kubectl rollout status deployment/php-app-deployment
          echo "Deployment successful!"
