name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Debug Kubeconfig
        run: |
          echo "Checking Kubeconfig content:"
          cat kubeconfig.yaml

      - name: Get pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods --kubeconfig=kubeconfig.yaml

      - name: Deploy akaunting-app
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f dep.yaml --kubeconfig=kubeconfig.yaml

      - name: Get deployment status
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/akaunting-app --kubeconfig=kubeconfig.yaml
